In [1]:
import pandas as pd
import numpy as np
#!pip install --upgrade scikit-learn
from platform import python_version
print(python_version())
#pip install -U imbalanced-learn
import imblearn

3.7.6


In [2]:
df= pd.read_excel('Dimension_Assigned_Data.xlsx')
df = df.rename(columns={'Manual_Polarity':'Label'})

In [3]:
df['Label']=np.where(df['Label']==999,0,df['Label'])

In [4]:
## Getting the Independent Features
X = df.drop(['Label'], axis=1)

In [5]:
## Get the Dependent Feature
y=df['Label']

In [6]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

In [7]:
corpus=[]
for i in X['Review']:
    corpus.append(i)

In [8]:
#cv = CountVectorizer(max_features=200,ngram_range=(2,4))
#X = cv.fit_transform(corpus).toarray() 

### TF-IDF

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
X = tf.fit_transform(corpus).toarray()

In [10]:
#corpus1=[]
#for i in test['Review']:
#    corpus1.append(i)
    
#test = tf.fit_transform(corpus1).toarray()    

In [11]:
X.shape

(685, 2036)

In [12]:
#test.shape

In [13]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

### Oversampling

### SMOTETomek

In [14]:
from imblearn.over_sampling import SMOTE
from collections import Counter
oversample = SMOTE()
X_train1, y_train1 = oversample.fit_resample(X_train, y_train)

In [15]:
#count_df = pd.DataFrame(X_train, columns=cv.get_feature_names())

In [16]:
#from imblearn.combine import SMOTETomek

#smk = SMOTETomek(random_state=42)
#X_res,y_res=smk.fit_resample(X_train,y_train)

#from collections import Counter
#print("The number of classes before fit {}".format(Counter(y_train)))
#print("The number of classes after fit {}".format(Counter(y_res)))

RandomOverSampler

In [17]:
#from imblearn.over_sampling import RandomOverSampler

In [18]:
#os = RandomOverSampler(0.75)
#X_r,y_r=smk.fit_resample(X_train,y_train)
#print("The number of classes before fit {}".format(Counter(y_train)))
#print("The number of classes after fit {}".format(Counter(y_r)))

### Applying MultinomialNB Algorithm

In [19]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [20]:
from sklearn import metrics
import numpy as np
import itertools

In [21]:
classifier.fit(X_train1, y_train1)
pred = classifier.predict(X_test)
score = metrics.accuracy_score(y_test, pred)
score

0.801762114537445

In [22]:
#test= pd.read_excel('New_Data.xlsx')
#test_pred= classifier.predict(test)

In [23]:
pred

array([ 0,  1,  0,  1,  0,  1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  0,  1,
        1,  1,  0,  1,  0,  0,  1,  0,  1, -1,  1,  1,  1,  1,  0,  1,  0,
        0, -1,  0,  0,  1, -1,  0,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1,
       -1, -1,  1,  1,  0,  1,  1,  0,  1,  1,  1,  0,  1,  1,  1,  1,  0,
        1,  1,  1,  1,  1,  1,  1,  0,  1, -1, -1,  1,  1, -1,  0,  0,  1,
        0,  1,  1,  0,  1,  1,  1,  1, -1, -1,  0,  1,  1,  0,  1,  1,  0,
        1,  0,  1, -1,  0, -1,  1,  1,  1, -1,  1,  0,  1,  1,  1,  0,  1,
       -1,  1,  0,  1,  0,  1,  1,  0,  1,  1,  1,  0, -1, -1,  1,  1,  1,
        0,  0,  0,  0,  1, -1,  0,  1,  0,  0,  1,  0, -1,  1,  1,  0,  1,
        1,  1,  1,  0,  1,  1,  1,  1, -1,  1, -1,  0,  1,  0,  1,  0,  0,
        1,  1,  0,  1,  0,  1,  1,  1, -1,  1,  0,  0,  1,  1,  1,  0, -1,
        1,  0, -1,  1,  1,  1, -1,  0,  1,  1,  0,  1,  1,  1, -1,  1,  1,
        0,  0,  1,  1,  0,  1,  0,  1, -1,  0,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  0

In [24]:
print(metrics.confusion_matrix(y_test,pred))

[[ 23   6   4]
 [  7  44  12]
 [  4  12 115]]


In [25]:
print(metrics.classification_report(y_test,pred,digits=3))
print("Accuracy: %.2f%%" % (score * 100.0))

              precision    recall  f1-score   support

          -1      0.676     0.697     0.687        33
           0      0.710     0.698     0.704        63
           1      0.878     0.878     0.878       131

    accuracy                          0.802       227
   macro avg      0.755     0.758     0.756       227
weighted avg      0.802     0.802     0.802       227

Accuracy: 80.18%
