In [51]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
import pandas as pd
import numpy as np

In [52]:
df= pd.read_excel('Dimension_Assigned_Data.xlsx')
df = df.rename(columns={'Manual_Polarity':'Label'})

In [53]:
##converting '999' to 0
#def con(val):
#    for i in val:
#        if i==999:
#            val=0
#    return val     

In [54]:
df['Label']=np.where(df['Label']==999,0,df['Label'])

In [55]:
X = df.drop(['Label'], axis=1)
y=df['Label']

In [56]:
corpus=[]
for i in X['Review']:
    corpus.append(i)

### TF-IDF

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
X = tf.fit_transform(corpus).toarray()

In [58]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

### Over-sampling

In [59]:
from imblearn.over_sampling import SMOTE
from collections import Counter
oversample = SMOTE()
X_train1, y_train1 = oversample.fit_resample(X_train, y_train)
from collections import Counter
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train1)))

The number of classes before fit Counter({1: 262, 0: 115, -1: 81})
The number of classes after fit Counter({0: 262, 1: 262, -1: 262})


### Applying Random Forest Classifier

In [60]:
classifier=RandomForestClassifier()
classifier.fit(X_train1,y_train1)

RandomForestClassifier()

In [61]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy: %.2f%%" % (accuracy_score(y_test,y_pred) * 100.0))

[[ 16   5  12]
 [  2  42  19]
 [  1  11 119]]
0.7797356828193832
              precision    recall  f1-score   support

          -1       0.84      0.48      0.62        33
           0       0.72      0.67      0.69        63
           1       0.79      0.91      0.85       131

    accuracy                           0.78       227
   macro avg       0.79      0.69      0.72       227
weighted avg       0.78      0.78      0.77       227

Accuracy: 77.97%


In [34]:
from imblearn.ensemble import EasyEnsembleClassifier

In [40]:
easy=EasyEnsembleClassifier()
easy.fit(X_train1,y_train1)

EasyEnsembleClassifier()

In [41]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 4  2  6]
 [ 0 20  1]
 [ 1 29 18]]
0.5185185185185185
              precision    recall  f1-score   support

          -1       0.80      0.33      0.47        12
           0       0.39      0.95      0.56        21
           1       0.72      0.38      0.49        48

    accuracy                           0.52        81
   macro avg       0.64      0.55      0.51        81
weighted avg       0.65      0.52      0.51        81

